version: '3.9'
services:
  sql:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=postgres
    volumes:
      - sql-data:/var/lib/postgresql/data
  nosql:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - nosql-data:/data/db
  server:
    build: ./
    image: server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SQL_DATABASE_URL=postgres://postgresuser:postgrespass@127.0.0.1:5432/postgres
    depends_on:
      sql:
        condition: service_healthy
      nosql:
        condition: service_healthy

volumes:
  sql-data:
  nosql-data: